services:
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    ports:
      - "27017:27017"
  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"

volumes:
  mongodb: